version: "3.3"
services: 
    db:
        image: mysql
        container_name: mysql_container
        command: --default-authentication-plugin=mysql_native_password       
        environment: 
            MYSQL_ROOT_PASSWORD: password
        networks: 
            - app-connect
        restart: always
        ports: 
            - '3316:3316'
    api:
        build: "."
        container_name: api_container
        restart: always
        ports: 
            - '3000:3000'
        networks: 
            - app-connect
        depends_on: 
            - db

networks: 
    app-connect:
        driver: bridge